### ISSUE TITLE
Debug Warnings

### ISSUE THREAD

**Issue by raza-web** [ahmedkaludi/schema-and-structured-data-for-wp#1471]
PHP warnings in the Schema and Structured Data plugin.

Helpscout link - https://secure.helpscout.net/conversation/1563312269/205309?folderId=4626537

![Debgug - Structured Schema](https://user-images.githubusercontent.com/67839276/124751787-a9888a00-df44-11eb-8211-9534dba9aea6.JPG)

**Comment by LeoKesler** [comment]
Almost the same error, it started at july, 04 . I will post it here, because it is similar.

`2021/07/09 00:26:41 [error] 508814#508814: *160346 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $kb_website_output in
 /var/www/www.mysite.com/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php on line 452

PHP message: PHP Warning:  Undefined variable $kb_website_output in
 /var/www/www.mysite.com/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php on line 485

PHP message: PHP Warning:  Undefined variable $kb_website_output in
 /var/www/www.mysite.com/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php on line 501

PHP message: PHP Warning:  Undefined variable $kb_website_output in
 /var/www/www.mysite.com/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php on line 520" 

while reading response header from upstream, client: 207.46.13.94, server: mysite.com, request: 
 "GET /tag/simpatias/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.0-fpm.sock:", host: "www.mysite.com"`

Latest stable wordpress, php 8.0, nginx.
