### ISSUE TITLE
Publisher url uses get_site_url but should use get_home_url

### ISSUE THREAD

**Issue by janvitos** [ahmedkaludi/schema-and-structured-data-for-wp#1660]
Hi,

Looking at my website's schema today, I noticed under Article that publisher url had /wordpress at the end (ex. https://www.example.com/wordpress).

Here's what the schema data looks like:

`"publisher":{"@type":"Organization","name":"example","url":"https:\/\/www.example.com\/wordpress"`

Looking at service.php, I noticed the following line of code (5456) :

`$publisher['publisher']['url'] = get_site_url();`

In reality, using get_site_url is problematic for any site that uses an extra directory as their home directory, like /wordpress (could be anything really). I believe get_home_url should be used instead as it reflects the actual home url of any website, regardless of the home directory.

Maybe you should also investigate everywhere else in the code where get_site_url is used as there might be other places where get_home_url should be used instead.

Thanks.

**Comment by ajithkumar072** [comment]
Hi @janvitos 

Thank you for your query. we have recreated the issues from my side.
we have change the site URL and create the schema type. we got the proper URL in schema json.

please create the new schema type and check. if there is any issues. please make a video URL or screenshot. so that we can go further updates

Please contact us via https://structured-data-for-wp.com/contact-us/

So we can rectify the issue
