### ISSUE TITLE
JSON Schema Getting Truncate

### ISSUE THREAD

**Issue by tahmidbintaslim** [ahmedkaludi/schema-and-structured-data-for-wp#2156]
Hi Support Team, 
I am using SASWP in a wordpress site. I am seeing that a long json data where schema is getting truncate.

**Comment by Sanjeevsetu** [comment]
Hi @tahmidbintaslim 

Thanks for contacting us. Could you share us url of the site so that we can check it?

**Comment by tahmidbintaslim** [comment]
https://marionskitchen.com/

**Comment by Sanjeevsetu** [comment]
@tahmidbintaslim 

I can see markup is there with Organization, Website and SiteNavigationElement schema included in it. What do mean by truncate here?? You might have missed some schema settings to get your desire result. Check our docs and better contact us through https://structured-data-for-wp.com/contact-us/

**Comment by tahmidbintaslim** [comment]
Hi @Sanjeevsetu ,

Can you please check below screenshot take from this [url](https://www.marionskitchen.com/korean-beef-stew-galbi-jjim/) where we see Truncate /cut off of the json schema ?

![image](https://github.com/user-attachments/assets/10be75aa-74fa-4561-aee7-ea53a83838b8)

**Comment by Sanjeevsetu** [comment]
Hi @tahmidbintaslim 

Its chrome browser console which shows you truncate schema due to there limitation, Its not a bug. you check full source here view-source:https://www.marionskitchen.com/korean-beef-stew-galbi-jjim/ or you can test using schema markup validator tool ( https://validator.schema.org/ ) and they are showing full Json-ld
