### ISSUE TITLE
Need to make compatibility with  DWQA Pro version plugin

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#372]
Ref:https://secure.helpscout.net/conversation/896153498/72797?folderId=2770543
NOTE:
User need to DWQA Pro version is compatibility in our plugin.

**Comment by Reacherrr** [comment]
We bought DWQA pro version for we trust the compatibility of the Schema & Structured Data for WP plug-in with the DWQA plug-in, but this feature  doesn't work as said.  So If the problem is not resolved quickly, we will complaint to WordPress.org and Ampforwp Company.

**Comment by ahmedkaludi** [comment]
Where did you buy dwqa from?

Did you buy our schema and structured data plug-in?

**Comment by Reacherrr** [comment]
I bought to DWQA plugin from offical sales website. I bought from as below link
https://codecanyon.net/item/dw-question-answer-pro-wordpress-plugin/15057949

The Schema and structured plugin's features page says it is compatible with DWQA.. But 
this plugin is not compatible. We bought  DWQA plugin because we trust  to be compatible.
We don't need to buy the Schema and Structured Data plug-in. This feature already in free version .

**Comment by ahmedkaludi** [comment]
If you try the free plugin, the option is already there: https://monosnap.com/file/KKRkQA2CdC8OHVpEpoKdXm8u0fERwK

It's the plugin which is: https://wordpress.org/plugins/dw-question-answer/
