### ISSUE TITLE
Need to add "bbpress" support with "Q&A Schema"

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#391]
Helpscout Link: https://secure.helpscout.net/conversation/903511274/73851?folderId=2770545

**Comment by sglotzer** [comment]
I do not have access/account in this platform
 
 
 
De: akashagrjsr <notifications@github.com> 
Enviado el: miércoles, 17 de julio de 2019 10:27
Para: ahmedkaludi/schema-and-structured-data-for-wp
<schema-and-structured-data-for-wp@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [ahmedkaludi/schema-and-structured-data-for-wp] Need to add "bbpress"
support with "Q&A Schema" (#391)
 
Helpscout Link:
https://secure.helpscout.net/conversation/903511274/73851?folderId=2770545

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/391?e
mail_source=notifications&email_token=AB3ULFL4UKMVZN4MQCGOH63P73JWHA5CNFSM4IEN
ZTBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7VHJ6A> , or mute the
thread
<https://t.sidekickopen10.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M
PwyRVRbB7z3ZSy2CF3J2C4jl11cf58tb6x03?te=W3R5hFj4cm2zwW3P28X24hCPvhW43T4P243X5b
gW3SYLpP3T1MdZW1LFyV_4hCWypW49M7TJ1Gy80dW3Qzvpd1VhmKzW2Yr1NJ36739BW3gg4zf2xR2J
zW2vPy2G2KHMW1W2TqDYK32mtXLw2xMjJ65Ln2&si=5637686686384128&pi=0503ecf9-b7aa-4f
e6-841f-29c529a5c30a> .
<https://github.com/notifications/beacon/AB3ULFPQ7RMUM4I7BVND5ATP73JWHA5CNFSM4
IENZTBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7VHJ6A.gif> 
 
<https://t.sidekickopen10.com/s1t/o/5/f18dQhb0S7ks8dDMPbW2n0x6l2B9gXrN7sKj6v5d
lR6W8qC8902m2NbDW3C8_yV72TN-Qf2K_lxx01?si=5637686686384128&pi=0503ecf9-b7aa-4f
e6-841f-29c529a5c30a>
