### ISSUE TITLE
CSS border-box rule causing issues

### ISSUE THREAD

**Issue by ckboyle** [ahmedkaludi/schema-and-structured-data-for-wp#420]
There is a global box-sizing CSS rule on line 1052 of the main-style.css file which is causing havoc for a number of other themes and plugins that we use.  It makes some dialog boxes simply unusable.  A rule with greater CSS specificity that isolates itself to only impact elements relevant to your plugin would be useful.

`/*** Review Module section ***/
*, *:before, *:after{
    box-sizing:border-box;
}`

**Comment by ahmedkaludi** [comment]
@ckboyle  I'm sorry for this, I will make sure that we fix this in the next update! 
**BUG**
- [ ] fixing above issue

- [ ] Get a review of  main-style.css from me.

**Comment by sglotzer** [comment]
Please, could you review way I am still in copy of these emails?
 
I am not subscribed!
 
Maybe I am in CC copy from you?
 
 
 

 
De: Ahmed Kaludi <notifications@github.com> 
Enviado el: jueves, 8 de agosto de 2019 11:08
Para: ahmedkaludi/schema-and-structured-data-for-wp
<schema-and-structured-data-for-wp@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [ahmedkaludi/schema-and-structured-data-for-wp] CSS border-box
rule causing issues (#420)
 
@ckboyle
<https://t.sidekickopen10.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M
PwyRVRbB7z3ZSy2CF3J2C4jl11cf58tb6x03?te=W3R5hFj4cm2zwW3P28X24hCPvhW43T4NS3XVr8
_38WR2&si=5637686686384128&pi=29ec89cf-00f2-40dd-bfaf-f9d59e95d0d1>  I'm sorry
for this, I will make sure that we fix this in the next update!
BUG
*	[ ] fixing above issue
*	[ ] Get a review of main-style.css from me.
-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread
<https://t.sidekickopen10.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M
PwyRVRbB7z3ZSy2CF3J2C4jl11cf58tb6x03?te=W3R5hFj4cm2zwW3P28X24hCPvhW43T4P243X5b
gW3SYLpP3T1MdZW1LFyV_4hCWypW49M7TJ1Gy80dW3Qzvpd1VhmKzW2HB_HK2qXG8BW2HsW1l3d7cG
FW2vP-Hs2Wj7yLW2TqDYK32mtXLw2Mv_TV7712&si=5637686686384128&pi=29ec89cf-00f2-40
dd-bfaf-f9d59e95d0d1> .
<https://github.com/notifications/beacon/AB3ULFNMGRHO3EFNTL77AULQDPO75A5CNFSM4
IKCSG72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD327NJA.gif
> 
 
<https://t.sidekickopen10.com/s1t/o/5/f18dQhb0S7ks8dDMPbW2n0x6l2B9gXrN7sKj6v5d
lR6W8qC8902m2NbDW3C8_yV72TN-Qf2K_lxx01?si=5637686686384128&pi=29ec89cf-00f2-40
dd-bfaf-f9d59e95d0d1>
