### ISSUE TITLE
Post specific schema fields are not showing on first button click inside custom post types

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/schema-and-structured-data-for-wp#424]
https://prnt.sc/oqdoiz

**Comment by sglotzer** [comment]
Why I am receiving these notificaction if I am unuscribe???
 
 

 
De: Sanjeev Kumar <notifications@github.com> 
Enviado el: viernes, 9 de agosto de 2019 8:48
Para: ahmedkaludi/schema-and-structured-data-for-wp
<schema-and-structured-data-for-wp@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [ahmedkaludi/schema-and-structured-data-for-wp] Post specific schema
fields are not showing on first enable on custom post types (#424)
 
https://prnt.sc/oqdoiz
-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread
<https://t.sidekickopen10.com/s1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3M
PwyRVRbB7z3ZSy2CF3J2C4jl11cf58tb6x03?te=W3R5hFj4cm2zwW3P28X24hCPvhW43T4P243X5b
gW3SYLpP3T1MdZW1LFyV_4hCWypW49M7TJ1Gy80dW3Qzvpd1VhmKzW2RxdcR2Rv6JVW1S3YsJ2Rlfr
RW2PBlK12FG50JW2TqDYK32mtXLw2MDcw45LC2&si=5637686686384128&pi=6ff81b44-ae50-48
ef-baf0-683a3c2852b3> .
<https://github.com/notifications/beacon/AB3ULFIBEACTBWTHO3EVKALQDUHLLA5CNFSM4
IKRBZNKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HEKJPUA.gif> 
 
<https://t.sidekickopen10.com/s1t/o/5/f18dQhb0S7ks8dDMPbW2n0x6l2B9gXrN7sKj6v5d
lR6W8qC8902m2NbDW3C8_yV72TN-Qf2K_lxx01?si=5637686686384128&pi=6ff81b44-ae50-48
ef-baf0-683a3c2852b3>
