### ISSUE TITLE
KK Star is not working anymore

### ISSUE THREAD

**Issue by babaamirhossein** [ahmedkaludi/schema-and-structured-data-for-wp#506]
hi, KK Star plugin rates are not showing anymore, Thus, aggregateRatings are null now and nothing is show for google.
KK Star plugin version: 3.1.2
Schema & Structured plugin version: 1.9.8
Wordpress: 5.2.3

**Comment by Sanjeevsetu** [comment]
Which type of schema you have added to your site. As recently google has announced some changes in rich snippets. Due to that changes we were force to remove aggregateRatings from (Article, NewsArticle, BlogPosting, TechArticle, WebPage etc...). Now AggregateRatings will work with these schema types ( https://developers.google.com/search/docs/data-types/review-snippet )

**Comment by babaamirhossein** [comment]
Hi,
I am using SoftwareApplication and Videogame. In the latest version of your
plugin, KK star rates are not added to the schema anymore for these two
schema I have mentioned. But in your old versions like 1.8.x it is fine.
Thank you

**Comment by Sanjeevsetu** [comment]
Have you modified those on post specifically?.

**Comment by Sanjeevsetu** [comment]
We tested it. and you are right. it should come with these schema types. This is a valid issue. We will fix it intermediately.

**Comment by babaamirhossein** [comment]
wohoo! I am now so surprised for your next update. Thanks for your time and
your great support.
