### ISSUE TITLE
Judge.me compatibility improvement.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/schema-and-structured-data-for-wp#571]
Judge.me compatibility improvement.
Ref: https://secure.helpscout.net/conversation/986408896/93317?folderId=2322651

**Comment by diegoversiani** [comment]
Hi there,

We are having issues with compatibility to Judge.me schema data on our client website.

Here is the fix we had applied before installing _schema-and-structured-data-for-wp_ on our website that we sent for to Judge.me authors (Remove Duplicated AggregateRating in Woocommerce): https://judgeme.freshdesk.com/support/solutions/articles/44001260256

Basically the issue that we had was with WooCommerce and also Judge.me generated the _aggregateRating_ node resulting in a duplication of the node.

Now our issue is that _schema-and-structured-data-for-wp_ is replacing the schema data generated by Judge.me with seemingly data from the database. Now we have 38 reviews on schema but the correct number is 136 which are visible on the product page to our customers.

I think the issue is that Judge.me doesn't store their reviews on our website but on their systems database so we don't have an accurate review data on our website so that _schema-and-structured-data-for-wp_ can hook to, also for some products we use a Judge.me feature to group reviews for grouped products.

**Comment by Sanjeevsetu** [comment]
Hi @diegoversiani,

Yes, We understand your concern and we are on it. We will fix it very quickly.

Please co-operate with us.

**Comment by Sanjeevsetu** [comment]
Hi @diegoversiani,

I would like to inform you that. Judge.me is not allowing to fetch reviews with woocommerce product id using reviews api so We are stuck on it. We are looking for alternative solutions

**Comment by Sanjeevsetu** [comment]
Do judge.me generate valid schema markup. I checked and can not see valid markup.

**Comment by Sanjeevsetu** [comment]
The problem is that they store all the reviews on their server not on yours. At any case we need to get those reviews by woo commerce product_id using api. But they are not allowing to get those reviews by woo  commerce product id. I have contacted them for this.
